// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY4C19duQpiPAyrEwp1HG8s6Ojqy6Dlos',
    appId: '1:1051924890756:web:11becfc77f452ceff9eed1',
    messagingSenderId: '1051924890756',
    projectId: 'smart-moves-2120a',
    authDomain: 'smart-moves-2120a.firebaseapp.com',
    storageBucket: 'smart-moves-2120a.firebasestorage.app',
    measurementId: 'G-TPY6KS6LM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8e9Z4Dsxxyt18vkDx3KuuXlZ26VTVNtg',
    appId: '1:1051924890756:android:3b118831c796945af9eed1',
    messagingSenderId: '1051924890756',
    projectId: 'smart-moves-2120a',
    storageBucket: 'smart-moves-2120a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUc_J71SJI7jJ0RJXxh4LovmeE4qCjHYE',
    appId: '1:1051924890756:ios:e171791b51eb2f02f9eed1',
    messagingSenderId: '1051924890756',
    projectId: 'smart-moves-2120a',
    storageBucket: 'smart-moves-2120a.firebasestorage.app',
    iosBundleId: 'com.example.smartMoves',
  );
}
